version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      # Add the backend URL that the frontend will use
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/database.sqlite
      # Add any other environment variables needed by your backend
    volumes:
      - backend_data:/app/data
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  backend_data:
    driver: local
