# docker-compose.yml for standalone Deno API
version: '3'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    volumes:
      - ./src:/app/src
      - ./data:/app/data
      - ./deno.json:/app/deno.json
      - ./import_map.json:/app/import_map.json
      - ./deps.ts:/app/deps.ts
    environment:
      - PORT=3000
      - NODE_ENV=production
      - ALLOWED_ORIGINS=http://localhost:3001,https://yourdomain.com
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'deno',
          'eval',
          "try { await fetch('http://localhost:3000/api/health'); Deno.exit(0) } catch(e) { Deno.exit(1) }"
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Optional: Database administration tool
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - api

# Define volumes for data persistence
volumes:
  data:
    driver: local
