# docker-compose.yml for standalone Deno API
version: '3.8'

services:
  api:
    build: .
    ports:
      - '3000:3000'
    volumes:
      - ./data:/app/data
    environment:
      - NODE_ENV=development
      - PORT=3000
      - DB_PATH=/app/data/database.sqlite
      - ALLOWED_ORIGINS=http://localhost:3000
    restart: unless-stopped
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:3000/api/health']
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Database administration tool
  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - '8080:8080'
    environment:
      - ADMINER_DEFAULT_SERVER=db
    depends_on:
      - api

# Define volumes for data persistence
volumes:
  data:
    driver: local
